version: '3.9'

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
      args:
        #- VITE_API_URL=http://my_production_backend:8000
        # we default to localhost for development
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
